service: koop-serverless-example

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x

functions:
  get-data:
    handler: src/index.handler
    events:
      - http:
          path: /pg-provider/{host}/FeatureServer/0
          method: get
          cors: true
          request:
            parameters:
              paths:
                host: true
  query-data:
    handler: src/index.handler
    events:
      - http:
          path: /pg-provider/{host}/FeatureServer/0/query
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                where: false
              paths:
                host: true
